#mysql
spring:
  datasource:
    url: jdbc:mysql://45.134.82.164:7004/webfile?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: lubao
    password: 84952139
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.mx.webfile.model
  configuration.map-underscore-to-camel-case: true

#固定访问前缀
file-http: http://nghome.mxliveplay.cn:7001/pic/

#FastDFS配置begin-----------除了fastdfs.tracker_servers，其它配置项都是可选的
fdfs:
  # 读取时间
  soTimeout: 1501
  # 连接超时时间
  connectTimeout: 691
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumb-image:
    # 宽
    width: 150
    # 高
    height: 150
  trackerList:
    - 45.134.82.164:7005
